export const FETCH_POSTS_LOADING = "FETCH_POSTS_LOADING";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";

export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
export const GET_POSTS = "GET_POSTS";

export const IS_MODAL_OPEN = "IS_MODAL_OPEN"
export const IS_MODAL_CLOSE = "IS_MODAL_CLOSE"

export const IS_UPDATING_OPEN = "IS_UPDATING_OPEN"
export const IS_UPDATING_CLOSE = "IS_UPDATING_CLOSE"